[features]
seeds = false
skip-lint = false
[programs.localnet]
lending_protocol = "EsRUR46kq9vBqzzqNwTUSyZDz7VDp6H6EoxQ44D8VYSw"
[programs.devnet]
lending_protocol = "EsRUR46kq9vBqzzqNwTUSyZDz7VDp6H6EoxQ44D8VYSw"
[programs.mainnet]
lending_protocol = "EsRUR46kq9vBqzzqNwTUSyZDz7VDp6H6EoxQ44D8VYSw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src && cp target/idl/lending_protocol.json app/src/idl.json"
